name: pluginPrueba
api: "1.13"
main: com.comugamers.spigot.Main
version: "1.0"
api-version: "1.13"
authors:
  - ComuGamers
commands:
  bastion1:
    description: Seleccionar primera esquina del bastion
  bastion2:
    description: Seleccionar segunda esquina del bastion
  eliminarbastion:
    description: Elimina el bastion del equipo
  getbastion:
    description: Obtiene las coordenadas del bastion de un equipo
  verbastion:
    description: Muestra el bastion de un equipo
  bloquearbastion:
    description: Impide que los jugadores de un equipo salgan de su bastion
  desbloquearbastion:
    description: Permite nuevamente salir del bastion al equipo indicado
