name: pluginPrueba
api: "1.13"
main: com.comugamers.spigot.Main
version: "1.0"
api-version: "1.13"
authors:
  - ComuGamers
commands:
  bastion1:
    description: Seleccionar primera esquina del bastion
  bastion2:
    description: Seleccionar segunda esquina del bastion
  eliminarbastion:
    description: Elimina el bastion del equipo
  getbastion:
    description: Obtiene las coordenadas del bastion de un equipo
  verbastion:
    description: Muestra el bastion de un equipo
  bloquearbastion:
    description: Impide que los jugadores de un equipo salgan de su bastion
  desbloquearbastion:
    description: Permite nuevamente salir del bastion al equipo indicado
  setzonaataque:
    description: Define la zona donde se teletransportarán los atacantes de un equipo
  iniciarataque:
    description: Teletransporta a los jugadores para iniciar la fase de ataque
  objetivopvp:
    description: Permite atacar al equipo indicado sin PVP entre los atacantes
  setcofre:
    description: Guarda el contenido de un cofre para un equipo
